services:
  app:
    build: .
    container_name: flask-test
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: flask-nginx
    ports:
      - "8080:80"   # przeglądarka → nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
