version: "3.9"

services:
  app:
    build: .
    container_name: flask-test
    ports:
      - "127.0.0.1:5000:5000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: flask-nginx
    ports:
      - "8080:80"   # przeglÄ…darka --> nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
